export { deriveInteractionLayers } from "./layers";
export type {
  DiscoverResult,
  LocatorField,
  LocatorMatch,
  LocatorNode,
  LocatorOperator,
  LocatorPredicate,
  LocatorQuery,
  LocatorValue,
  RematchResult,
} from "./locator";
export {
  discoverLocators,
  findLocators,
  matchesLocator,
  parseLocator,
  rematchLocator,
} from "./locator";
export {
  applyVomInteractionRecovery,
  isVomReferenceNode,
  isVomStructuralRole,
  prepareObservationRender,
  projectVom,
  type RenderRow,
  renderCompactVom,
  renderVom,
} from "./render";
export type {
  ActiveScopeBlock,
  BlockingLayer,
  CondSurface,
  InteractionLayer,
  LayerKind,
  Rect,
  RenderedRef,
  Viewport,
  VisualEntry,
  VomCompleteness,
  VomNode,
  VomOptions,
  VomProjection,
  VomProjectionNode,
  VomRef,
  VomRelation,
  VomResult,
  VomScene,
  VomVirtualizedListEvidence,
} from "./types";
export type {
  CollectVirtualizedOptions,
  CollectVirtualizedResult,
  FrontierExhaustion,
  FrontierIdentityStatus,
  ListFrontier,
  ListFrontierContext,
  ListFrontierUpdate,
  ListFrontierWindow,
  RestoreListFrontierOptions,
  VirtualizedAdvance,
  VirtualizedCompleteness,
  VirtualizedListAnalysis,
  VirtualizedSegment,
} from "./virtualized";
export {
  analyzeVirtualizedLists,
  collectVirtualizedSegments,
  createListFrontier,
  invalidateListFrontier,
  recordListFrontierWindow,
  restoreListFrontier,
  serializeListFrontier,
  stableItemFingerprint,
} from "./virtualized";
